export const filtersOperations = {
  GT: "gt",
  GTE: "gte",
  LT: "lt",
  LTE: "lte",
  EQUAL: "equal",
  NOT_EQUAL: "not equal",
  CONTAINS: "contains",
  IN: "in",
  NOT_IN: "not in",
  IS_NULL: "is null",
  IS_NOT_NULL: "is not null",
  IS_EMPTY: "is empty",
  IS_NOT_EMPTY: "is not empty",
  BETWEEN: "between",
  IS_NULL_OR_NOT_EQUAL: "is null or not equal",
  STARTS_WITH: "starts with",
  ENDS_WITH: "ends with",
  OR: "or",
  AND: "and",
  NOT: "not",
  TRUE: "true",
  FALSE: "false",
};
