import { IConfigurationBackdoor } from "../../types/api/configuratorBackdoor";

export const activeBackdoorFakeData: IConfigurationBackdoor = {
  result: {
    ID: {
      type: "integer",
      isRequired: false,
      isReadOnly: true,
      isImmutable: false,
      isMultiple: false,
      isDynamic: false,
      title: "ID",
    },
    TITLE: {
      type: "string",
      isRequired: false,
      isReadOnly: false,
      isImmutable: false,
      isMultiple: false,
      isDynamic: false,
      title: "Название лида",
    },
    HONORIFIC: {
      type: "crm_status",
      isRequired: false,
      isReadOnly: false,
      isImmutable: false,
      isMultiple: false,
      isDynamic: false,
      statusType: "HONORIFIC",
      title: "Обращение",
    },
    NAME: {
      type: "string",
      isRequired: false,
      isReadOnly: false,
      isImmutable: false,
      isMultiple: false,
      isDynamic: false,
      title: "Имя",
    },
    SECOND_NAME: {
      type: "string",
      isRequired: false,
      isReadOnly: false,
      isImmutable: false,
      isMultiple: false,
      isDynamic: false,
      title: "Отчество",
    },
    LAST_NAME: {
      type: "string",
      isRequired: false,
      isReadOnly: false,
      isImmutable: false,
      isMultiple: false,
      isDynamic: false,
      title: "Фамилия",
    },
    BIRTHDATE: {
      type: "date",
      isRequired: false,
      isReadOnly: false,
      isImmutable: false,
      isMultiple: false,
      isDynamic: false,
      title: "Дата рождения",
    },
    COMPANY_TITLE: {
      type: "string",
      isRequired: false,
      isReadOnly: false,
      isImmutable: false,
      isMultiple: false,
      isDynamic: false,
      title: "Название компании",
    },
    SOURCE_ID: {
      type: "crm_status",
      isRequired: false,
      isReadOnly: false,
      isImmutable: false,
      isMultiple: false,
      isDynamic: false,
      statusType: "SOURCE",
      title: "Источник",
    },
    SOURCE_DESCRIPTION: {
      type: "string",
      isRequired: false,
      isReadOnly: false,
      isImmutable: false,
      isMultiple: false,
      isDynamic: false,
      title: "Дополнительно об источнике",
    },
    STATUS_ID: {
      type: "crm_status",
      isRequired: false,
      isReadOnly: false,
      isImmutable: false,
      isMultiple: false,
      isDynamic: false,
      statusType: "STATUS",
      title: "Стадия",
    },
    STATUS_DESCRIPTION: {
      type: "string",
      isRequired: false,
      isReadOnly: false,
      isImmutable: false,
      isMultiple: false,
      isDynamic: false,
      title: "Дополнительно о стадии",
    },
    STATUS_SEMANTIC_ID: {
      type: "string",
      isRequired: false,
      isReadOnly: true,
      isImmutable: false,
      isMultiple: false,
      isDynamic: false,
      title: "Состояние статуса",
    },
    POST: {
      type: "string",
      isRequired: false,
      isReadOnly: false,
      isImmutable: false,
      isMultiple: false,
      isDynamic: false,
      title: "Должность",
    },
    ADDRESS: {
      type: "string",
      isRequired: false,
      isReadOnly: false,
      isImmutable: false,
      isMultiple: false,
      isDynamic: false,
      title: "Адрес",
    },
    ADDRESS_2: {
      type: "string",
      isRequired: false,
      isReadOnly: false,
      isImmutable: false,
      isMultiple: false,
      isDynamic: false,
      title: "Адрес (стр. 2)",
    },
    ADDRESS_CITY: {
      type: "string",
      isRequired: false,
      isReadOnly: false,
      isImmutable: false,
      isMultiple: false,
      isDynamic: false,
      title: "Город",
    },
    ADDRESS_POSTAL_CODE: {
      type: "string",
      isRequired: false,
      isReadOnly: false,
      isImmutable: false,
      isMultiple: false,
      isDynamic: false,
      title: "Почтовый индекс",
    },
    ADDRESS_REGION: {
      type: "string",
      isRequired: false,
      isReadOnly: false,
      isImmutable: false,
      isMultiple: false,
      isDynamic: false,
      title: "Район",
    },
    ADDRESS_PROVINCE: {
      type: "string",
      isRequired: false,
      isReadOnly: false,
      isImmutable: false,
      isMultiple: false,
      isDynamic: false,
      title: "Область",
    },
    ADDRESS_COUNTRY: {
      type: "string",
      isRequired: false,
      isReadOnly: false,
      isImmutable: false,
      isMultiple: false,
      isDynamic: false,
      title: "Страна",
    },
    ADDRESS_COUNTRY_CODE: {
      type: "string",
      isRequired: false,
      isReadOnly: false,
      isImmutable: false,
      isMultiple: false,
      isDynamic: false,
      title: "Код страны",
    },
    ADDRESS_LOC_ADDR_ID: {
      type: "integer",
      isRequired: false,
      isReadOnly: false,
      isImmutable: false,
      isMultiple: false,
      isDynamic: false,
      title: "Идентификатор адреса местоположения",
    },
    CURRENCY_ID: {
      type: "crm_currency",
      isRequired: false,
      isReadOnly: false,
      isImmutable: false,
      isMultiple: false,
      isDynamic: false,
      title: "Валюта",
    },
    OPPORTUNITY: {
      type: "double",
      isRequired: false,
      isReadOnly: false,
      isImmutable: false,
      isMultiple: false,
      isDynamic: false,
      title: "Сумма",
    },
    IS_MANUAL_OPPORTUNITY: {
      type: "char",
      isRequired: false,
      isReadOnly: false,
      isImmutable: false,
      isMultiple: false,
      isDynamic: false,
      title: "IS_MANUAL_OPPORTUNITY",
    },
    OPENED: {
      type: "char",
      isRequired: false,
      isReadOnly: false,
      isImmutable: false,
      isMultiple: false,
      isDynamic: false,
      title: "Доступен для всех",
    },
    COMMENTS: {
      type: "string",
      isRequired: false,
      isReadOnly: false,
      isImmutable: false,
      isMultiple: false,
      isDynamic: false,
      title: "Комментарий",
    },
    HAS_PHONE: {
      type: "char",
      isRequired: false,
      isReadOnly: true,
      isImmutable: false,
      isMultiple: false,
      isDynamic: false,
      title: "Задан телефон",
    },
    HAS_EMAIL: {
      type: "char",
      isRequired: false,
      isReadOnly: true,
      isImmutable: false,
      isMultiple: false,
      isDynamic: false,
      title: "Задан e-mail",
    },
    HAS_IMOL: {
      type: "char",
      isRequired: false,
      isReadOnly: true,
      isImmutable: false,
      isMultiple: false,
      isDynamic: false,
      title: "Задана открытая линия",
    },
    ASSIGNED_BY_ID: {
      type: "user",
      isRequired: false,
      isReadOnly: false,
      isImmutable: false,
      isMultiple: false,
      isDynamic: false,
      title: "Ответственный",
    },
    CREATED_BY_ID: {
      type: "user",
      isRequired: false,
      isReadOnly: true,
      isImmutable: false,
      isMultiple: false,
      isDynamic: false,
      title: "Кем создан",
    },
    MODIFY_BY_ID: {
      type: "user",
      isRequired: false,
      isReadOnly: true,
      isImmutable: false,
      isMultiple: false,
      isDynamic: false,
      title: "Кем изменен",
    },
    MOVED_BY_ID: {
      type: "user",
      isRequired: false,
      isReadOnly: true,
      isImmutable: false,
      isMultiple: false,
      isDynamic: false,
      title: "MOVED_BY_ID",
    },
    DATE_CREATE: {
      type: "datetime",
      isRequired: false,
      isReadOnly: true,
      isImmutable: false,
      isMultiple: false,
      isDynamic: false,
      title: "Дата создания",
    },
    DATE_MODIFY: {
      type: "datetime",
      isRequired: false,
      isReadOnly: true,
      isImmutable: false,
      isMultiple: false,
      isDynamic: false,
      title: "Дата изменения",
    },
    MOVED_TIME: {
      type: "datetime",
      isRequired: false,
      isReadOnly: true,
      isImmutable: false,
      isMultiple: false,
      isDynamic: false,
      title: "MOVED_TIME",
    },
    COMPANY_ID: {
      type: "crm_company",
      isRequired: false,
      isReadOnly: false,
      isImmutable: false,
      isMultiple: false,
      isDynamic: false,
      title: "Компания",
      settings: {
        parentEntityTypeId: 4,
      },
    },
    CONTACT_ID: {
      type: "crm_contact",
      isRequired: false,
      isReadOnly: false,
      isImmutable: false,
      isMultiple: false,
      isDynamic: false,
      isDeprecated: true,
      title: "Контакт",
    },
    CONTACT_IDS: {
      type: "crm_contact",
      isRequired: false,
      isReadOnly: false,
      isImmutable: false,
      isMultiple: true,
      isDynamic: false,
      title: "CONTACT_IDS",
    },
    IS_RETURN_CUSTOMER: {
      type: "char",
      isRequired: false,
      isReadOnly: true,
      isImmutable: false,
      isMultiple: false,
      isDynamic: false,
      title: "Повторный лид",
      settings: undefined,
    },
    DATE_CLOSED: {
      type: "datetime",
      isRequired: false,
      isReadOnly: true,
      isImmutable: false,
      isMultiple: false,
      isDynamic: false,
      title: "Дата завершения",
    },
    ORIGINATOR_ID: {
      type: "string",
      isRequired: false,
      isReadOnly: false,
      isImmutable: false,
      isMultiple: false,
      isDynamic: false,
      title: "Внешний источник",
    },
    ORIGIN_ID: {
      type: "string",
      isRequired: false,
      isReadOnly: false,
      isImmutable: false,
      isMultiple: false,
      isDynamic: false,
      title: "Идентификатор элемента во внешнем источнике",
    },
    UTM_SOURCE: {
      type: "string",
      isRequired: false,
      isReadOnly: false,
      isImmutable: false,
      isMultiple: false,
      isDynamic: false,
      title: "Рекламная система",
    },
    UTM_MEDIUM: {
      type: "string",
      isRequired: false,
      isReadOnly: false,
      isImmutable: false,
      isMultiple: false,
      isDynamic: false,
      title: "Тип трафика",
    },
    UTM_CAMPAIGN: {
      type: "string",
      isRequired: false,
      isReadOnly: false,
      isImmutable: false,
      isMultiple: false,
      isDynamic: false,
      title: "Обозначение рекламной кампании",
    },
    UTM_CONTENT: {
      type: "string",
      isRequired: false,
      isReadOnly: false,
      isImmutable: false,
      isMultiple: false,
      isDynamic: false,
      title: "Содержание кампании",
    },
    UTM_TERM: {
      type: "string",
      isRequired: false,
      isReadOnly: false,
      isImmutable: false,
      isMultiple: false,
      isDynamic: false,
      title: "Условие поиска кампании",
    },
    LAST_ACTIVITY_TIME: {
      type: "datetime",
      isRequired: false,
      isReadOnly: true,
      isImmutable: false,
      isMultiple: false,
      isDynamic: false,
      title: "LAST_ACTIVITY_TIME",
    },
    LAST_ACTIVITY_BY: {
      type: "user",
      isRequired: false,
      isReadOnly: true,
      isImmutable: false,
      isMultiple: false,
      isDynamic: false,
      title: "LAST_ACTIVITY_BY",
    },
    PHONE: {
      type: "crm_multifield",
      isRequired: false,
      isReadOnly: false,
      isImmutable: false,
      isMultiple: true,
      isDynamic: false,
      title: "Телефон",
    },
    EMAIL: {
      type: "crm_multifield",
      isRequired: false,
      isReadOnly: false,
      isImmutable: false,
      isMultiple: true,
      isDynamic: false,
      title: "E-mail",
    },
    WEB: {
      type: "crm_multifield",
      isRequired: false,
      isReadOnly: false,
      isImmutable: false,
      isMultiple: true,
      isDynamic: false,
      title: "Сайт",
    },
    IM: {
      type: "crm_multifield",
      isRequired: false,
      isReadOnly: false,
      isImmutable: false,
      isMultiple: true,
      isDynamic: false,
      title: "Мессенджер",
    },
    LINK: {
      type: "crm_multifield",
      isRequired: false,
      isReadOnly: false,
      isImmutable: false,
      isMultiple: true,
      isDynamic: false,
      title: "LINK",
    },
    UF_CRM_1652972714: {
      type: "boolean",
      isRequired: false,
      isReadOnly: false,
      isImmutable: false,
      isMultiple: false,
      isDynamic: true,
      title: "UF_CRM_1652972714",
      listLabel: "Новый Лид",
      formLabel: "Новый Лид",
      filterLabel: "Новый Лид",
      settings: {},
    },
    UF_CRM_LGB_CITY: {
      type: "string",
      isRequired: false,
      isReadOnly: false,
      isImmutable: false,
      isMultiple: false,
      isDynamic: true,
      title: "UF_CRM_LGB_CITY",
      listLabel: "Город",
      formLabel: "Город",
      filterLabel: "UF_CRM_LGB_CITY",
      settings: {
        SIZE: 20,
        ROWS: 1,
        REGEXP: "",
        MIN_LENGTH: 0,
        MAX_LENGTH: 0,
        DEFAULT_VALUE: "",
      },
    },
    UF_CRM_LGB_SUMM: {
      type: "string",
      isRequired: false,
      isReadOnly: false,
      isImmutable: false,
      isMultiple: false,
      isDynamic: true,
      title: "UF_CRM_LGB_SUMM",
      listLabel: "Долг",
      formLabel: "Долг",
      filterLabel: "UF_CRM_LGB_SUMM",
      settings: {
        SIZE: 20,
        ROWS: 1,
        REGEXP: "",
        MIN_LENGTH: 0,
        MAX_LENGTH: 0,
        DEFAULT_VALUE: "",
      },
    },
    UF_CRM_LGB_KEY: {
      type: "string",
      isRequired: false,
      isReadOnly: false,
      isImmutable: false,
      isMultiple: false,
      isDynamic: true,
      title: "UF_CRM_LGB_KEY",
      listLabel: "Ключевое слово LBG",
      formLabel: "Ключевое слово LBG",
      filterLabel: "UF_CRM_LGB_KEY",
      settings: {
        SIZE: 20,
        ROWS: 1,
        REGEXP: "",
        MIN_LENGTH: 0,
        MAX_LENGTH: 0,
        DEFAULT_VALUE: "",
      },
    },
    UF_CRM_LGB_OVER: {
      type: "string",
      isRequired: false,
      isReadOnly: false,
      isImmutable: false,
      isMultiple: false,
      isDynamic: true,
      title: "UF_CRM_LGB_OVER",
      listLabel: "Просрочка",
      formLabel: "Просрочка",
      filterLabel: "UF_CRM_LGB_OVER",
      settings: {
        SIZE: 20,
        ROWS: 1,
        REGEXP: "",
        MIN_LENGTH: 0,
        MAX_LENGTH: 0,
        DEFAULT_VALUE: "",
      },
    },
    UF_CRM_LGB_REGION: {
      type: "string",
      isRequired: false,
      isReadOnly: false,
      isImmutable: false,
      isMultiple: false,
      isDynamic: true,
      title: "UF_CRM_LGB_REGION",
      listLabel: "Регион LBG",
      formLabel: "Регион LBG",
      filterLabel: "UF_CRM_LGB_REGION",
      settings: {
        SIZE: 20,
        ROWS: 1,
        REGEXP: "",
        MIN_LENGTH: 0,
        MAX_LENGTH: 0,
        DEFAULT_VALUE: "",
      },
    },
    UF_CRM_ID_PACK: {
      type: "string",
      isRequired: false,
      isReadOnly: false,
      isImmutable: false,
      isMultiple: false,
      isDynamic: true,
      title: "UF_CRM_ID_PACK",
      listLabel: "ID пакета",
      formLabel: "ID пакета",
      filterLabel: "UF_CRM_ID_PACK",
      settings: {
        SIZE: 20,
        ROWS: 1,
        REGEXP: "",
        MIN_LENGTH: 0,
        MAX_LENGTH: 0,
        DEFAULT_VALUE: "",
      },
    },
    UF_CRM_LGB_WHAT: {
      type: "string",
      isRequired: false,
      isReadOnly: false,
      isImmutable: false,
      isMultiple: false,
      isDynamic: true,
      title: "UF_CRM_LGB_WHAT",
      listLabel: "Что хочет",
      formLabel: "Что хочет",
      filterLabel: "UF_CRM_LGB_WHAT",
      settings: {
        SIZE: 20,
        ROWS: 1,
        REGEXP: "",
        MIN_LENGTH: 0,
        MAX_LENGTH: 0,
        DEFAULT_VALUE: "",
      },
    },
    UF_CRM_LGB_PAY: {
      type: "string",
      isRequired: false,
      isReadOnly: false,
      isImmutable: false,
      isMultiple: false,
      isDynamic: true,
      title: "UF_CRM_LGB_PAY",
      listLabel: "Ежемесячный платеж",
      formLabel: "Ежемесячный платеж",
      filterLabel: "UF_CRM_LGB_PAY",
      settings: {
        SIZE: 20,
        ROWS: 1,
        REGEXP: "",
        MIN_LENGTH: 0,
        MAX_LENGTH: 0,
        DEFAULT_VALUE: "",
      },
    },
    UF_CRM_TRANID: {
      type: "string",
      isRequired: false,
      isReadOnly: false,
      isImmutable: false,
      isMultiple: false,
      isDynamic: true,
      title: "UF_CRM_TRANID",
      listLabel: "UF_CRM_TRANID",
      formLabel: "UF_CRM_TRANID",
      filterLabel: "UF_CRM_TRANID",
      settings: {
        SIZE: 20,
        ROWS: 1,
        REGEXP: "",
        MIN_LENGTH: 0,
        MAX_LENGTH: 0,
        DEFAULT_VALUE: "",
      },
    },
    UF_CRM_LGB_PROBLEM: {
      type: "string",
      isRequired: false,
      isReadOnly: false,
      isImmutable: false,
      isMultiple: false,
      isDynamic: true,
      title: "UF_CRM_LGB_PROBLEM",
      listLabel: "Ситуация клиента",
      formLabel: "Ситуация клиента",
      filterLabel: "UF_CRM_LGB_PROBLEM",
      settings: {
        SIZE: 20,
        ROWS: 1,
        REGEXP: "",
        MIN_LENGTH: 0,
        MAX_LENGTH: 0,
        DEFAULT_VALUE: "",
      },
    },
    UF_CRM_INSTAGRAM_WZ: {
      type: "string",
      isRequired: false,
      isReadOnly: false,
      isImmutable: false,
      isMultiple: false,
      isDynamic: true,
      title: "UF_CRM_INSTAGRAM_WZ",
      listLabel: "Instagram_WZ",
      formLabel: "Instagram_WZ",
      filterLabel: "UF_CRM_INSTAGRAM_WZ",
      settings: {
        SIZE: 20,
        ROWS: 1,
        REGEXP: "",
        MIN_LENGTH: 0,
        MAX_LENGTH: 0,
        DEFAULT_VALUE: "",
      },
    },
    UF_CRM_VK_WZ: {
      type: "string",
      isRequired: false,
      isReadOnly: false,
      isImmutable: false,
      isMultiple: false,
      isDynamic: true,
      title: "UF_CRM_VK_WZ",
      listLabel: "VK_WZ",
      formLabel: "VK_WZ",
      filterLabel: "UF_CRM_VK_WZ",
      settings: {
        SIZE: 20,
        ROWS: 1,
        REGEXP: "",
        MIN_LENGTH: 0,
        MAX_LENGTH: 0,
        DEFAULT_VALUE: "",
      },
    },
    UF_CRM_AVITO_WZ: {
      type: "string",
      isRequired: false,
      isReadOnly: false,
      isImmutable: false,
      isMultiple: false,
      isDynamic: true,
      title: "UF_CRM_AVITO_WZ",
      listLabel: "Avito_WZ",
      formLabel: "Avito_WZ",
      filterLabel: "UF_CRM_AVITO_WZ",
      settings: {
        SIZE: 20,
        ROWS: 1,
        REGEXP: "",
        MIN_LENGTH: 0,
        MAX_LENGTH: 0,
        DEFAULT_VALUE: "",
      },
    },
    UF_CRM_TELEGRAMUSERNAME_WZ: {
      type: "string",
      isRequired: false,
      isReadOnly: false,
      isImmutable: false,
      isMultiple: false,
      isDynamic: true,
      title: "UF_CRM_TELEGRAMUSERNAME_WZ",
      listLabel: "TelegramUsername_WZ",
      formLabel: "TelegramUsername_WZ",
      filterLabel: "UF_CRM_TELEGRAMUSERNAME_WZ",
      settings: {
        SIZE: 20,
        ROWS: 1,
        REGEXP: "",
        MIN_LENGTH: 0,
        MAX_LENGTH: 0,
        DEFAULT_VALUE: "",
      },
    },
    UF_CRM_TELEGRAMID_WZ: {
      type: "string",
      isRequired: false,
      isReadOnly: false,
      isImmutable: false,
      isMultiple: false,
      isDynamic: true,
      title: "UF_CRM_TELEGRAMID_WZ",
      listLabel: "TelegramId_WZ",
      formLabel: "TelegramId_WZ",
      filterLabel: "UF_CRM_TELEGRAMID_WZ",
      settings: {
        SIZE: 20,
        ROWS: 1,
        REGEXP: "",
        MIN_LENGTH: 0,
        MAX_LENGTH: 0,
        DEFAULT_VALUE: "",
      },
    },
    UF_CRM_1691594636697: {
      type: "enumeration",
      isRequired: false,
      isReadOnly: false,
      isImmutable: false,
      isMultiple: false,
      isDynamic: true,
      items: [
        {
          ID: "254",
          VALUE: "Приоритет 1",
        },
        {
          ID: "256",
          VALUE: "Приоритет 2",
        },
        {
          ID: "258",
          VALUE: "Приоритет 3",
        },
      ],
      title: "UF_CRM_1691594636697",
      listLabel: "Приоритет лида",
      formLabel: "Приоритет лида",
      filterLabel: "Приоритет лида",
      settings: {
        DISPLAY: "UI",
        LIST_HEIGHT: 1,
        CAPTION_NO_VALUE: "",
        SHOW_NO_VALUE: "Y",
      },
    },
    UF_CRM_OLCHATWASTATS: {
      type: "rest_18_olchat_wa_stats",
      isRequired: false,
      isReadOnly: false,
      isImmutable: false,
      isMultiple: false,
      isDynamic: true,
      title: "UF_CRM_OLCHATWASTATS",
      listLabel: "OLChat — статусы и чаты",
      formLabel: "OLChat — статусы и чаты",
      filterLabel: "UF_CRM_OLCHATWASTATS",
      settings: [],
    },
    UF_CRM_1691758536255: {
      type: "datetime",
      isRequired: false,
      isReadOnly: false,
      isImmutable: false,
      isMultiple: false,
      isDynamic: true,
      title: "UF_CRM_1691758536255",
      listLabel: "Новая дата",
      formLabel: "Новая дата",
      filterLabel: "Новая дата",
      settings: {
        DEFAULT_VALUE: {
          TYPE: "NONE",
          VALUE: "",
        },
        USE_SECOND: "Y",
        USE_TIMEZONE: "N",
      },
    },
    UF_CRM_1692027422886: {
      type: "string",
      isRequired: false,
      isReadOnly: false,
      isImmutable: false,
      isMultiple: false,
      isDynamic: true,
      title: "UF_CRM_1692027422886",
      listLabel: "Проверка ватсап на номере (тех поле)",
      formLabel: "Проверка ватсап на номере (тех поле)",
      filterLabel: "Проверка ватсап на номере (тех поле)",
      settings: {
        SIZE: 20,
        ROWS: 1,
        REGEXP: "",
        MIN_LENGTH: 0,
        MAX_LENGTH: 0,
        DEFAULT_VALUE: null,
      },
    },
    UF_CRM_1692347253951: {
      type: "enumeration",
      isRequired: false,
      isReadOnly: false,
      isImmutable: false,
      isMultiple: false,
      isDynamic: true,
      items: [
        {
          ID: "266",
          VALUE: "Ливинский Денис",
        },
        {
          ID: "268",
          VALUE: "Младшнева Галина",
        },
      ],
      title: "UF_CRM_1692347253951",
      listLabel: "Чей лид",
      formLabel: "Чей лид",
      filterLabel: "Чей лид",
      settings: {
        DISPLAY: "UI",
        LIST_HEIGHT: 1,
        CAPTION_NO_VALUE: "",
        SHOW_NO_VALUE: "Y",
      },
    },
    UF_CRM_1692953704467: {
      type: "enumeration",
      isRequired: false,
      isReadOnly: false,
      isImmutable: false,
      isMultiple: false,
      isDynamic: true,
      items: [
        {
          ID: "294",
          VALUE: "# пьяный клиент",
        },
        {
          ID: "296",
          VALUE: "# нецензурная речь",
        },
        {
          ID: "298",
          VALUE: "# не нужна наша помощь",
        },
        {
          ID: "300",
          VALUE: "# залоговый",
        },
        {
          ID: "302",
          VALUE: "# не оставлял заявки",
        },
        {
          ID: "304",
          VALUE: "# нет денег вообще",
        },
        {
          ID: "306",
          VALUE: "# хотел бесплатно",
        },
        {
          ID: "308",
          VALUE: "# негативщик",
        },
        {
          ID: "310",
          VALUE: "# Болеет",
        },
        {
          ID: "312",
          VALUE: "# После инсульта (плохо разговаривает)",
        },
        {
          ID: "314",
          VALUE: "#С инвалидностью",
        },
        {
          ID: "360",
          VALUE: "#Битый номер",
        },
      ],
      title: "UF_CRM_1692953704467",
      listLabel: "# хештег",
      formLabel: "# хештег",
      filterLabel: "# хештег",
      settings: {
        DISPLAY: "UI",
        LIST_HEIGHT: 1,
        CAPTION_NO_VALUE: "",
        SHOW_NO_VALUE: "Y",
      },
    },
    UF_CRM_T_IMA: {
      type: "string",
      isRequired: false,
      isReadOnly: false,
      isImmutable: false,
      isMultiple: false,
      isDynamic: true,
      title: "UF_CRM_T_IMA",
      listLabel: "Имя (из flexbe)",
      formLabel: "Имя",
      filterLabel: "UF_CRM_T_IMA",
      settings: {
        SIZE: 20,
        ROWS: 1,
        REGEXP: "",
        MIN_LENGTH: 0,
        MAX_LENGTH: 0,
        DEFAULT_VALUE: "",
      },
    },
    UF_CRM_P_TELEFON: {
      type: "string",
      isRequired: false,
      isReadOnly: false,
      isImmutable: false,
      isMultiple: false,
      isDynamic: true,
      title: "UF_CRM_P_TELEFON",
      listLabel: "Телефон (из flexbe)",
      formLabel: "Телефон",
      filterLabel: "UF_CRM_P_TELEFON",
      settings: {
        SIZE: 20,
        ROWS: 1,
        REGEXP: "",
        MIN_LENGTH: 0,
        MAX_LENGTH: 0,
        DEFAULT_VALUE: "",
      },
    },
    UF_CRM_R_UKAZITESUMM: {
      type: "string",
      isRequired: false,
      isReadOnly: false,
      isImmutable: false,
      isMultiple: false,
      isDynamic: true,
      title: "UF_CRM_R_UKAZITESUMM",
      listLabel: "Укажите сумму ваших долгов (из flexbe)",
      formLabel: "Укажите сумму ваших долгов",
      filterLabel: "UF_CRM_R_UKAZITESUMM",
      settings: {
        SIZE: 20,
        ROWS: 1,
        REGEXP: "",
        MIN_LENGTH: 0,
        MAX_LENGTH: 0,
        DEFAULT_VALUE: "",
      },
    },
    UF_CRM_BT_PODSKAZITE: {
      type: "string",
      isRequired: false,
      isReadOnly: false,
      isImmutable: false,
      isMultiple: false,
      isDynamic: true,
      title: "UF_CRM_BT_PODSKAZITE",
      listLabel: "Подскажите, какие долги вы хотели бы списать? (из flexbe)",
      formLabel: "Подскажите, какие долги вы хотели бы списать?",
      filterLabel: "UF_CRM_BT_PODSKAZITE",
      settings: {
        SIZE: 20,
        ROWS: 1,
        REGEXP: "",
        MIN_LENGTH: 0,
        MAX_LENGTH: 0,
        DEFAULT_VALUE: "",
      },
    },
    UF_CRM_R_ESTLIUVASZA: {
      type: "string",
      isRequired: false,
      isReadOnly: false,
      isImmutable: false,
      isMultiple: false,
      isDynamic: true,
      title: "UF_CRM_R_ESTLIUVASZA",
      listLabel: "Есть ли у вас залоговое / ипотечное имущество? (из flexbe)",
      formLabel: "Есть ли у вас залоговое / ипотечное имущество?",
      filterLabel: "UF_CRM_R_ESTLIUVASZA",
      settings: {
        SIZE: 20,
        ROWS: 1,
        REGEXP: "",
        MIN_LENGTH: 0,
        MAX_LENGTH: 0,
        DEFAULT_VALUE: "",
      },
    },
    UF_CRM_R_REGIONVKOTO: {
      type: "string",
      isRequired: false,
      isReadOnly: false,
      isImmutable: false,
      isMultiple: false,
      isDynamic: true,
      title: "UF_CRM_R_REGIONVKOTO",
      listLabel: "Регион в котором находитесь? (из flexbe)",
      formLabel: "Регион в котором находитесь?",
      filterLabel: "UF_CRM_R_REGIONVKOTO",
      settings: {
        SIZE: 20,
        ROWS: 1,
        REGEXP: "",
        MIN_LENGTH: 0,
        MAX_LENGTH: 0,
        DEFAULT_VALUE: "",
      },
    },
    UF_CRM_R_KAKUDOBNEEP: {
      type: "string",
      isRequired: false,
      isReadOnly: false,
      isImmutable: false,
      isMultiple: false,
      isDynamic: true,
      title: "UF_CRM_R_KAKUDOBNEEP",
      listLabel: "Как удобнее получить информацию? (из flexbe)",
      formLabel: "Как удобнее получить информацию?",
      filterLabel: "UF_CRM_R_KAKUDOBNEEP",
      settings: {
        SIZE: 20,
        ROWS: 1,
        REGEXP: "",
        MIN_LENGTH: 0,
        MAX_LENGTH: 0,
        DEFAULT_VALUE: "",
      },
    },
    UF_CRM_T_STRANICA: {
      type: "string",
      isRequired: false,
      isReadOnly: false,
      isImmutable: false,
      isMultiple: false,
      isDynamic: true,
      title: "UF_CRM_T_STRANICA",
      listLabel: "Страница (из flexbe)",
      formLabel: "Страница",
      filterLabel: "UF_CRM_T_STRANICA",
      settings: {
        SIZE: 20,
        ROWS: 1,
        REGEXP: "",
        MIN_LENGTH: 0,
        MAX_LENGTH: 0,
        DEFAULT_VALUE: "",
      },
    },
    UF_CRM_T_NAZVANIEFOR: {
      type: "string",
      isRequired: false,
      isReadOnly: false,
      isImmutable: false,
      isMultiple: false,
      isDynamic: true,
      title: "UF_CRM_T_NAZVANIEFOR",
      listLabel: "Название формы (из flexbe)",
      formLabel: "Название формы",
      filterLabel: "UF_CRM_T_NAZVANIEFOR",
      settings: {
        SIZE: 20,
        ROWS: 1,
        REGEXP: "",
        MIN_LENGTH: 0,
        MAX_LENGTH: 0,
        DEFAULT_VALUE: "",
      },
    },
    UF_CRM_T_URL: {
      type: "string",
      isRequired: false,
      isReadOnly: false,
      isImmutable: false,
      isMultiple: false,
      isDynamic: true,
      title: "UF_CRM_T_URL",
      listLabel: "url (из flexbe)",
      formLabel: "url",
      filterLabel: "UF_CRM_T_URL",
      settings: {
        SIZE: 20,
        ROWS: 1,
        REGEXP: "",
        MIN_LENGTH: 0,
        MAX_LENGTH: 0,
        DEFAULT_VALUE: "",
      },
    },
    UF_CRM_T_IP: {
      type: "string",
      isRequired: false,
      isReadOnly: false,
      isImmutable: false,
      isMultiple: false,
      isDynamic: true,
      title: "UF_CRM_T_IP",
      listLabel: "ip (из flexbe)",
      formLabel: "ip",
      filterLabel: "UF_CRM_T_IP",
      settings: {
        SIZE: 20,
        ROWS: 1,
        REGEXP: "",
        MIN_LENGTH: 0,
        MAX_LENGTH: 0,
        DEFAULT_VALUE: "",
      },
    },
    UF_CRM_T_UTMSOURCE: {
      type: "string",
      isRequired: false,
      isReadOnly: false,
      isImmutable: false,
      isMultiple: false,
      isDynamic: true,
      title: "UF_CRM_T_UTMSOURCE",
      listLabel: "utm_source (из flexbe)",
      formLabel: "utm_source",
      filterLabel: "UF_CRM_T_UTMSOURCE",
      settings: {
        SIZE: 20,
        ROWS: 1,
        REGEXP: "",
        MIN_LENGTH: 0,
        MAX_LENGTH: 0,
        DEFAULT_VALUE: "",
      },
    },
    UF_CRM_R_KOLICESTVOK: {
      type: "string",
      isRequired: false,
      isReadOnly: false,
      isImmutable: false,
      isMultiple: false,
      isDynamic: true,
      title: "UF_CRM_R_KOLICESTVOK",
      listLabel:
        "Количество кредитов и кредитных карт во всех банках (из flexbe)",
      formLabel: "Количество кредитов и кредитных карт во всех банках",
      filterLabel: "UF_CRM_R_KOLICESTVOK",
      settings: {
        SIZE: 20,
        ROWS: 1,
        REGEXP: "",
        MIN_LENGTH: 0,
        MAX_LENGTH: 0,
        DEFAULT_VALUE: "",
      },
    },
    UF_CRM_R_OBSAASUMMAZ: {
      type: "string",
      isRequired: false,
      isReadOnly: false,
      isImmutable: false,
      isMultiple: false,
      isDynamic: true,
      title: "UF_CRM_R_OBSAASUMMAZ",
      listLabel:
        "Общая сумма задолженности перед кредитными организациями (из flexbe)",
      formLabel: "Общая сумма задолженности перед кредитными организациями",
      filterLabel: "UF_CRM_R_OBSAASUMMAZ",
      settings: {
        SIZE: 20,
        ROWS: 1,
        REGEXP: "",
        MIN_LENGTH: 0,
        MAX_LENGTH: 0,
        DEFAULT_VALUE: "",
      },
    },
    UF_CRM_R_ESTLIUVASIP: {
      type: "string",
      isRequired: false,
      isReadOnly: false,
      isImmutable: false,
      isMultiple: false,
      isDynamic: true,
      title: "UF_CRM_R_ESTLIUVASIP",
      listLabel: "Есть ли у вас ипотека или автокредит? (из flexbe)",
      formLabel: "Есть ли у вас ипотека или автокредит?",
      filterLabel: "UF_CRM_R_ESTLIUVASIP",
      settings: {
        SIZE: 20,
        ROWS: 1,
        REGEXP: "",
        MIN_LENGTH: 0,
        MAX_LENGTH: 0,
        DEFAULT_VALUE: "",
      },
    },
    UF_CRM_R_VASGORODPOM: {
      type: "string",
      isRequired: false,
      isReadOnly: false,
      isImmutable: false,
      isMultiple: false,
      isDynamic: true,
      title: "UF_CRM_R_VASGORODPOM",
      listLabel: "Ваш город по месту регистрации (из flexbe)",
      formLabel: "Ваш город по месту регистрации",
      filterLabel: "UF_CRM_R_VASGORODPOM",
      settings: {
        SIZE: 20,
        ROWS: 1,
        REGEXP: "",
        MIN_LENGTH: 0,
        MAX_LENGTH: 0,
        DEFAULT_VALUE: "",
      },
    },
    UF_CRM_T_YMCLIENTID: {
      type: "string",
      isRequired: false,
      isReadOnly: false,
      isImmutable: false,
      isMultiple: false,
      isDynamic: true,
      title: "UF_CRM_T_YMCLIENTID",
      listLabel: "ym_client_id (из flexbe)",
      formLabel: "ym_client_id",
      filterLabel: "UF_CRM_T_YMCLIENTID",
      settings: {
        SIZE: 20,
        ROWS: 1,
        REGEXP: "",
        MIN_LENGTH: 0,
        MAX_LENGTH: 0,
        DEFAULT_VALUE: "",
      },
    },
    UF_CRM_R_KAKAAOBSAAS: {
      type: "string",
      isRequired: false,
      isReadOnly: false,
      isImmutable: false,
      isMultiple: false,
      isDynamic: true,
      title: "UF_CRM_R_KAKAAOBSAAS",
      listLabel: "Какая общая сумма долга? (из flexbe)",
      formLabel: "Какая общая сумма долга?",
      filterLabel: "UF_CRM_R_KAKAAOBSAAS",
      settings: {
        SIZE: 20,
        ROWS: 1,
        REGEXP: "",
        MIN_LENGTH: 0,
        MAX_LENGTH: 0,
        DEFAULT_VALUE: "",
      },
    },
    UF_CRM_R_ESTLIUVASAV: {
      type: "string",
      isRequired: false,
      isReadOnly: false,
      isImmutable: false,
      isMultiple: false,
      isDynamic: true,
      title: "UF_CRM_R_ESTLIUVASAV",
      listLabel: "Есть ли у вас автокредит / ипотечное имущество? (из flexbe)",
      formLabel: "Есть ли у вас автокредит / ипотечное имущество?",
      filterLabel: "UF_CRM_R_ESTLIUVASAV",
      settings: {
        SIZE: 20,
        ROWS: 1,
        REGEXP: "",
        MIN_LENGTH: 0,
        MAX_LENGTH: 0,
        DEFAULT_VALUE: "",
      },
    },
    UF_CRM_T_UTMMEDIUM: {
      type: "string",
      isRequired: false,
      isReadOnly: false,
      isImmutable: false,
      isMultiple: false,
      isDynamic: true,
      title: "UF_CRM_T_UTMMEDIUM",
      listLabel: "utm_medium (из flexbe)",
      formLabel: "utm_medium",
      filterLabel: "UF_CRM_T_UTMMEDIUM",
      settings: {
        SIZE: 20,
        ROWS: 1,
        REGEXP: "",
        MIN_LENGTH: 0,
        MAX_LENGTH: 0,
        DEFAULT_VALUE: "",
      },
    },
    UF_CRM_T_UTMCAMPAIGN: {
      type: "string",
      isRequired: false,
      isReadOnly: false,
      isImmutable: false,
      isMultiple: false,
      isDynamic: true,
      title: "UF_CRM_T_UTMCAMPAIGN",
      listLabel: "utm_campaign (из flexbe)",
      formLabel: "utm_campaign",
      filterLabel: "UF_CRM_T_UTMCAMPAIGN",
      settings: {
        SIZE: 20,
        ROWS: 1,
        REGEXP: "",
        MIN_LENGTH: 0,
        MAX_LENGTH: 0,
        DEFAULT_VALUE: "",
      },
    },
    UF_CRM_T_UTMCONTENT: {
      type: "string",
      isRequired: false,
      isReadOnly: false,
      isImmutable: false,
      isMultiple: false,
      isDynamic: true,
      title: "UF_CRM_T_UTMCONTENT",
      listLabel: "utm_content (из flexbe)",
      formLabel: "utm_content",
      filterLabel: "UF_CRM_T_UTMCONTENT",
      settings: {
        SIZE: 20,
        ROWS: 1,
        REGEXP: "",
        MIN_LENGTH: 0,
        MAX_LENGTH: 0,
        DEFAULT_VALUE: "",
      },
    },
    UF_CRM_T_UTMTERM: {
      type: "string",
      isRequired: false,
      isReadOnly: false,
      isImmutable: false,
      isMultiple: false,
      isDynamic: true,
      title: "UF_CRM_T_UTMTERM",
      listLabel: "utm_term (из flexbe)",
      formLabel: "utm_term",
      filterLabel: "UF_CRM_T_UTMTERM",
      settings: {
        SIZE: 20,
        ROWS: 1,
        REGEXP: "",
        MIN_LENGTH: 0,
        MAX_LENGTH: 0,
        DEFAULT_VALUE: "",
      },
    },
    UF_CRM_CH_PODSKAZITE: {
      type: "boolean",
      isRequired: false,
      isReadOnly: false,
      isImmutable: false,
      isMultiple: false,
      isDynamic: true,
      title: "UF_CRM_CH_PODSKAZITE",
      listLabel: "Подскажите, какие долги вы хотели бы списать? (из flexbe)",
      formLabel: "Подскажите, какие долги вы хотели бы списать?",
      filterLabel: "UF_CRM_CH_PODSKAZITE",
      settings: {
        DEFAULT_VALUE: 0,
        DISPLAY: "CHECKBOX",
        LABEL: ["", ""],
        LABEL_CHECKBOX: "",
      },
    },
    UF_CRM_T_IPLOCATION: {
      type: "string",
      isRequired: false,
      isReadOnly: false,
      isImmutable: false,
      isMultiple: false,
      isDynamic: true,
      title: "UF_CRM_T_IPLOCATION",
      listLabel: "ip_location (из flexbe)",
      formLabel: "ip_location",
      filterLabel: "UF_CRM_T_IPLOCATION",
      settings: {
        SIZE: 20,
        ROWS: 1,
        REGEXP: "",
        MIN_LENGTH: 0,
        MAX_LENGTH: 0,
        DEFAULT_VALUE: "",
      },
    },
    UF_CRM_MGO_CC_ENTRY_ID: {
      type: "string",
      isRequired: false,
      isReadOnly: false,
      isImmutable: false,
      isMultiple: false,
      isDynamic: true,
      title: "UF_CRM_MGO_CC_ENTRY_ID",
      listLabel: "ID звонка",
      formLabel: "ID звонка",
      filterLabel: "ID звонка",
      settings: {
        SIZE: 20,
        ROWS: 1,
        REGEXP: "",
        MIN_LENGTH: 0,
        MAX_LENGTH: 0,
        DEFAULT_VALUE: "",
      },
    },
    UF_CRM_MGO_CC_CHANNEL_TYPE: {
      type: "string",
      isRequired: false,
      isReadOnly: false,
      isImmutable: false,
      isMultiple: false,
      isDynamic: true,
      title: "UF_CRM_MGO_CC_CHANNEL_TYPE",
      listLabel: "Канал обращения",
      formLabel: "Канал обращения",
      filterLabel: "Канал обращения",
      settings: {
        SIZE: 20,
        ROWS: 1,
        REGEXP: "",
        MIN_LENGTH: 0,
        MAX_LENGTH: 0,
        DEFAULT_VALUE: "",
      },
    },
    UF_CRM_MGO_CC_RESULT: {
      type: "string",
      isRequired: false,
      isReadOnly: false,
      isImmutable: false,
      isMultiple: false,
      isDynamic: true,
      title: "UF_CRM_MGO_CC_RESULT",
      listLabel: "Результат обращения",
      formLabel: "Результат обращения",
      filterLabel: "Результат обращения",
      settings: {
        SIZE: 20,
        ROWS: 1,
        REGEXP: "",
        MIN_LENGTH: 0,
        MAX_LENGTH: 0,
        DEFAULT_VALUE: "",
      },
    },
    UF_CRM_MGO_CC_ENTRY_POINT: {
      type: "string",
      isRequired: false,
      isReadOnly: false,
      isImmutable: false,
      isMultiple: false,
      isDynamic: true,
      title: "UF_CRM_MGO_CC_ENTRY_POINT",
      listLabel: "Точка входа обращения",
      formLabel: "Точка входа обращения",
      filterLabel: "Точка входа обращения",
      settings: {
        SIZE: 20,
        ROWS: 1,
        REGEXP: "",
        MIN_LENGTH: 0,
        MAX_LENGTH: 0,
        DEFAULT_VALUE: "",
      },
    },
    UF_CRM_MGO_CC_CREATE: {
      type: "datetime",
      isRequired: false,
      isReadOnly: false,
      isImmutable: false,
      isMultiple: false,
      isDynamic: true,
      title: "UF_CRM_MGO_CC_CREATE",
      listLabel: "Дата/время создания обращения",
      formLabel: "Дата/время создания обращения",
      filterLabel: "Дата/время создания обращения",
      settings: {
        DEFAULT_VALUE: {
          TYPE: "NONE",
          VALUE: "",
        },
        USE_SECOND: "Y",
        USE_TIMEZONE: "N",
      },
    },
    UF_CRM_MGO_CC_END: {
      type: "datetime",
      isRequired: false,
      isReadOnly: false,
      isImmutable: false,
      isMultiple: false,
      isDynamic: true,
      title: "UF_CRM_MGO_CC_END",
      listLabel: "Дата/время завершения обращения",
      formLabel: "Дата/время завершения обращения",
      filterLabel: "Дата/время завершения обращения",
      settings: {
        DEFAULT_VALUE: {
          TYPE: "NONE",
          VALUE: "",
        },
        USE_SECOND: "Y",
        USE_TIMEZONE: "N",
      },
    },
    UF_CRM_MGO_CC_TAG_ID: {
      type: "string",
      isRequired: false,
      isReadOnly: false,
      isImmutable: false,
      isMultiple: false,
      isDynamic: true,
      title: "UF_CRM_MGO_CC_TAG_ID",
      listLabel: "Тематики обращения",
      formLabel: "Тематики обращения",
      filterLabel: "Тематики обращения",
      settings: {
        SIZE: 20,
        ROWS: 1,
        REGEXP: "",
        MIN_LENGTH: 0,
        MAX_LENGTH: 0,
        DEFAULT_VALUE: "",
      },
    },
    UF_CRM_FORMNAME: {
      type: "string",
      isRequired: false,
      isReadOnly: false,
      isImmutable: false,
      isMultiple: false,
      isDynamic: true,
      title: "UF_CRM_FORMNAME",
      listLabel: "UF_CRM_FORMNAME",
      formLabel: "UF_CRM_FORMNAME",
      filterLabel: "UF_CRM_FORMNAME",
      settings: {
        SIZE: 20,
        ROWS: 1,
        REGEXP: "",
        MIN_LENGTH: 0,
        MAX_LENGTH: 0,
        DEFAULT_VALUE: "",
      },
    },
    UF_CRM_1652972726: {
      type: "boolean",
      isRequired: false,
      isReadOnly: false,
      isImmutable: false,
      isMultiple: false,
      isDynamic: true,
      title: "UF_CRM_1652972726",
      listLabel: "Был на встрече/Анкета получена",
      formLabel: "Был на встрече/Анкета получена",
      filterLabel: "Был на встрече/Анкета получена",
      settings: {
        DEFAULT_VALUE: 0,
        DISPLAY: "RADIO",
        LABEL: [null, null],
        LABEL_CHECKBOX: "Был на встрече/Анкета получена",
      },
    },
    UF_CRM_1652972738: {
      type: "boolean",
      isRequired: false,
      isReadOnly: false,
      isImmutable: false,
      isMultiple: false,
      isDynamic: true,
      title: "UF_CRM_1652972738",
      listLabel: "Сделка заключена",
      formLabel: "Сделка заключена",
      filterLabel: "Сделка заключена",
      settings: {
        DEFAULT_VALUE: 0,
        DISPLAY: "RADIO",
        LABEL: [null, null],
        LABEL_CHECKBOX: "Сделка заключена",
      },
    },
    UF_CRM_1652972761: {
      type: "double",
      isRequired: false,
      isReadOnly: false,
      isImmutable: false,
      isMultiple: false,
      isDynamic: true,
      title: "UF_CRM_1652972761",
      listLabel: "Сумма всех кредитов",
      formLabel: "Сумма всех кредитов",
      filterLabel: "Сумма всех кредитов",
      settings: {
        PRECISION: 2,
        SIZE: 20,
        MIN_VALUE: 0,
        MAX_VALUE: 0,
        DEFAULT_VALUE: null,
      },
    },
    UF_CRM_1652972776: {
      type: "double",
      isRequired: false,
      isReadOnly: false,
      isImmutable: false,
      isMultiple: false,
      isDynamic: true,
      title: "UF_CRM_1652972776",
      listLabel: "Количество кредитов и кредитных карт",
      formLabel: "Количество кредитов и кредитных карт",
      filterLabel: "Количество кредитов и кредитных карт",
      settings: {
        PRECISION: 2,
        SIZE: 20,
        MIN_VALUE: 0,
        MAX_VALUE: 0,
        DEFAULT_VALUE: null,
      },
    },
    UF_CRM_1652972790: {
      type: "double",
      isRequired: false,
      isReadOnly: false,
      isImmutable: false,
      isMultiple: false,
      isDynamic: true,
      title: "UF_CRM_1652972790",
      listLabel: "Ежемесячный платеж по всем кредитам, картам и займам",
      formLabel: "Ежемесячный платеж по всем кредитам, картам и займам",
      filterLabel: "Ежемесячный платеж по всем кредитам, картам и займам",
      settings: {
        PRECISION: 2,
        SIZE: 20,
        MIN_VALUE: 0,
        MAX_VALUE: 0,
        DEFAULT_VALUE: null,
      },
    },
    UF_CRM_1652972815: {
      type: "enumeration",
      isRequired: false,
      isReadOnly: false,
      isImmutable: false,
      isMultiple: false,
      isDynamic: true,
      items: [
        {
          ID: "44",
          VALUE: "Нет просрочек",
        },
        {
          ID: "46",
          VALUE: "От 1 до 30 дней",
        },
        {
          ID: "48",
          VALUE: "От 30 до 60 дней",
        },
        {
          ID: "50",
          VALUE: "Более 90 дней",
        },
      ],
      title: "UF_CRM_1652972815",
      listLabel: "Срок просрочки по кредитам",
      formLabel: "Срок просрочки по кредитам",
      filterLabel: "Срок просрочки по кредитам",
      settings: {
        DISPLAY: "LIST",
        LIST_HEIGHT: 1,
        CAPTION_NO_VALUE: "",
        SHOW_NO_VALUE: "Y",
      },
    },
    UF_CRM_1652972830: {
      type: "double",
      isRequired: false,
      isReadOnly: false,
      isImmutable: false,
      isMultiple: false,
      isDynamic: true,
      title: "UF_CRM_1652972830",
      listLabel:
        "Сколько требуют Банки и МФО сейчас к погашению (чтобы войти в график)",
      formLabel:
        "Сколько требуют Банки и МФО сейчас к погашению (чтобы войти в график)",
      filterLabel:
        "Сколько требуют Банки и МФО сейчас к погашению (чтобы войти в график)",
      settings: {
        PRECISION: 2,
        SIZE: 20,
        MIN_VALUE: 0,
        MAX_VALUE: 0,
        DEFAULT_VALUE: null,
      },
    },
    UF_CRM_1652972845: {
      type: "double",
      isRequired: false,
      isReadOnly: false,
      isImmutable: false,
      isMultiple: false,
      isDynamic: true,
      title: "UF_CRM_1652972845",
      listLabel:
        "Официальный ежемесячный дохода на данный момент (з/п, пенсия, иное)",
      formLabel:
        "Официальный ежемесячный дохода на данный момент (з/п, пенсия, иное)",
      filterLabel:
        "Официальный ежемесячный дохода на данный момент (з/п, пенсия, иное)",
      settings: {
        PRECISION: 2,
        SIZE: 20,
        MIN_VALUE: 0,
        MAX_VALUE: 0,
        DEFAULT_VALUE: null,
      },
    },
    UF_CRM_1652972863: {
      type: "double",
      isRequired: false,
      isReadOnly: false,
      isImmutable: false,
      isMultiple: false,
      isDynamic: true,
      title: "UF_CRM_1652972863",
      listLabel: "Фактический ежемесячный доход",
      formLabel: "Фактический ежемесячный доход",
      filterLabel: "Фактический ежемесячный доход",
      settings: {
        PRECISION: 2,
        SIZE: 20,
        MIN_VALUE: 0,
        MAX_VALUE: 0,
        DEFAULT_VALUE: null,
      },
    },
    UF_CRM_1652972876: {
      type: "string",
      isRequired: false,
      isReadOnly: false,
      isImmutable: false,
      isMultiple: false,
      isDynamic: true,
      title: "UF_CRM_1652972876",
      listLabel: "Кем работает клиент",
      formLabel: "Кем работает клиент",
      filterLabel: "Кем работает клиент",
      settings: {
        SIZE: 20,
        ROWS: 1,
        REGEXP: "",
        MIN_LENGTH: 0,
        MAX_LENGTH: 0,
        DEFAULT_VALUE: "",
      },
    },
    UF_CRM_1652972898: {
      type: "enumeration",
      isRequired: false,
      isReadOnly: false,
      isImmutable: false,
      isMultiple: false,
      isDynamic: true,
      items: [
        {
          ID: "52",
          VALUE: "Женат/Замужем",
        },
        {
          ID: "54",
          VALUE: "Холост",
        },
        {
          ID: "56",
          VALUE: "Неизвестно",
        },
      ],
      title: "UF_CRM_1652972898",
      listLabel: "Семейное положение",
      formLabel: "Семейное положение",
      filterLabel: "Семейное положение",
      settings: {
        DISPLAY: "LIST",
        LIST_HEIGHT: 1,
        CAPTION_NO_VALUE: "",
        SHOW_NO_VALUE: "Y",
      },
    },
    UF_CRM_1652972918: {
      type: "enumeration",
      isRequired: false,
      isReadOnly: false,
      isImmutable: false,
      isMultiple: false,
      isDynamic: true,
      items: [
        {
          ID: "58",
          VALUE: "Да",
        },
        {
          ID: "60",
          VALUE: "Нет",
        },
        {
          ID: "62",
          VALUE: "Неизвестно",
        },
      ],
      title: "UF_CRM_1652972918",
      listLabel: "Несовершеннолетние дети",
      formLabel: "Несовершеннолетние дети",
      filterLabel: "Несовершеннолетние дети",
      settings: {
        DISPLAY: "LIST",
        LIST_HEIGHT: 1,
        CAPTION_NO_VALUE: "",
        SHOW_NO_VALUE: "Y",
      },
    },
    UF_CRM_1652972931: {
      type: "string",
      isRequired: false,
      isReadOnly: false,
      isImmutable: false,
      isMultiple: false,
      isDynamic: true,
      title: "UF_CRM_1652972931",
      listLabel: "Имущество",
      formLabel: "Имущество",
      filterLabel: "Имущество",
      settings: {
        SIZE: 20,
        ROWS: 1,
        REGEXP: "",
        MIN_LENGTH: 0,
        MAX_LENGTH: 0,
        DEFAULT_VALUE: "",
      },
    },
    UF_CRM_1652972957: {
      type: "string",
      isRequired: false,
      isReadOnly: false,
      isImmutable: false,
      isMultiple: false,
      isDynamic: true,
      title: "UF_CRM_1652972957",
      listLabel: "Почему возникла сложная ситуация?",
      formLabel: "Почему возникла сложная ситуация?",
      filterLabel: "Почему возникла сложная ситуация?",
      settings: {
        SIZE: 20,
        ROWS: 1,
        REGEXP: "",
        MIN_LENGTH: 0,
        MAX_LENGTH: 0,
        DEFAULT_VALUE: "",
      },
    },
    UF_CRM_1652972980: {
      type: "enumeration",
      isRequired: false,
      isReadOnly: false,
      isImmutable: false,
      isMultiple: false,
      isDynamic: true,
      items: [
        {
          ID: "64",
          VALUE: "Уменьшить платежи",
        },
        {
          ID: "66",
          VALUE: "Реструктуризация",
        },
        {
          ID: "68",
          VALUE: "Полностью списать все кредиты и долги",
        },
      ],
      title: "UF_CRM_1652972980",
      listLabel: "Что хотел бы получить в конечном итоге",
      formLabel: "Что хотел бы получить в конечном итоге",
      filterLabel: "Что хотел бы получить в конечном итоге",
      settings: {
        DISPLAY: "LIST",
        LIST_HEIGHT: 1,
        CAPTION_NO_VALUE: "",
        SHOW_NO_VALUE: "Y",
      },
    },
    UF_CRM_1652972996: {
      type: "double",
      isRequired: false,
      isReadOnly: false,
      isImmutable: false,
      isMultiple: false,
      isDynamic: true,
      title: "UF_CRM_1652972996",
      listLabel: "Сумма первого платежа (внес при заключении договора)",
      formLabel: "Сумма первого платежа (внес при заключении договора)",
      filterLabel: "Сумма первого платежа (внес при заключении договора)",
      settings: {
        PRECISION: 2,
        SIZE: 20,
        MIN_VALUE: 0,
        MAX_VALUE: 0,
        DEFAULT_VALUE: null,
      },
    },
    UF_CRM_1652973010: {
      type: "file",
      isRequired: false,
      isReadOnly: false,
      isImmutable: false,
      isMultiple: false,
      isDynamic: true,
      title: "UF_CRM_1652973010",
      listLabel: "Загрузить анкету клиента",
      formLabel: "Загрузить анкету клиента",
      filterLabel: "Загрузить анкету клиента",
      settings: {
        SIZE: 20,
        LIST_WIDTH: 0,
        LIST_HEIGHT: 0,
        MAX_SHOW_SIZE: 0,
        MAX_ALLOWED_SIZE: 0,
        EXTENSIONS: [],
        TARGET_BLANK: "Y",
      },
    },
    UF_CRM_1652973026: {
      type: "datetime",
      isRequired: false,
      isReadOnly: false,
      isImmutable: false,
      isMultiple: false,
      isDynamic: true,
      title: "UF_CRM_1652973026",
      listLabel: "Дата и время назначенной встречи",
      formLabel: "Дата и время назначенной встречи",
      filterLabel: "Дата и время назначенной встречи",
      settings: {
        DEFAULT_VALUE: {
          TYPE: "NONE",
          VALUE: "",
        },
        USE_SECOND: "Y",
        USE_TIMEZONE: "N",
      },
    },
    UF_CRM_1652973054: {
      type: "enumeration",
      isRequired: false,
      isReadOnly: false,
      isImmutable: false,
      isMultiple: false,
      isDynamic: true,
      items: [
        {
          ID: "70",
          VALUE: "Да",
        },
        {
          ID: "72",
          VALUE: "Нет",
        },
      ],
      title: "UF_CRM_1652973054",
      listLabel: "Онлайн",
      formLabel: "Онлайн",
      filterLabel: "Онлайн",
      settings: {
        DISPLAY: "LIST",
        LIST_HEIGHT: 1,
        CAPTION_NO_VALUE: "",
        SHOW_NO_VALUE: "Y",
      },
    },
    UF_CRM_1652973069: {
      type: "double",
      isRequired: false,
      isReadOnly: false,
      isImmutable: false,
      isMultiple: false,
      isDynamic: true,
      title: "UF_CRM_1652973069",
      listLabel: "Полная стоимость по договору",
      formLabel: "Полная стоимость по договору",
      filterLabel: "Полная стоимость по договору",
      settings: {
        PRECISION: 2,
        SIZE: 20,
        MIN_VALUE: 0,
        MAX_VALUE: 0,
        DEFAULT_VALUE: null,
      },
    },
    UF_CRM_1652973090: {
      type: "double",
      isRequired: false,
      isReadOnly: false,
      isImmutable: false,
      isMultiple: false,
      isDynamic: true,
      title: "UF_CRM_1652973090",
      listLabel: "Остаток",
      formLabel: "Остаток",
      filterLabel: "Остаток",
      settings: {
        PRECISION: 2,
        SIZE: 20,
        MIN_VALUE: 0,
        MAX_VALUE: 0,
        DEFAULT_VALUE: null,
      },
    },
    UF_CRM_1652973101: {
      type: "date",
      isRequired: false,
      isReadOnly: false,
      isImmutable: false,
      isMultiple: false,
      isDynamic: true,
      title: "UF_CRM_1652973101",
      listLabel: "Дата следующей оплаты",
      formLabel: "Дата следующей оплаты",
      filterLabel: "Дата следующей оплаты",
      settings: {
        DEFAULT_VALUE: {
          TYPE: "NONE",
          VALUE: "",
        },
      },
    },
    UF_CRM_1652973111: {
      type: "string",
      isRequired: false,
      isReadOnly: false,
      isImmutable: false,
      isMultiple: false,
      isDynamic: true,
      title: "UF_CRM_1652973111",
      listLabel: "График платежей",
      formLabel: "График платежей",
      filterLabel: "График платежей",
      settings: {
        SIZE: 20,
        ROWS: 12,
        REGEXP: "",
        MIN_LENGTH: 0,
        MAX_LENGTH: 0,
        DEFAULT_VALUE: "",
      },
    },
  },
  time: {
    start: 1738173455.429763,
    finish: 1738173455.47702,
    duration: 0.0472569465637207,
    processing: 0.012335062026977539,
    date_start: "2025-01-29T20:57:35+03:00",
    date_finish: "2025-01-29T20:57:35+03:00",
    operating_reset_at: 1738174055,
    operating: 0,
  },
};
